steps:
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        # ---- Configuración del Entorno de Build ----

        apt-get update && apt-get install -y unzip curl git openjdk-17-jdk

        FLUTTER_VERSION='3.22.0-stable'

        curl -O https://storage.googleapis.com/flutter_releases/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}.tar.xz
        tar xvf flutter_linux_${FLUTTER_VERSION}.tar.xz --directory /workspace/

        export PATH="$PATH:/workspace/flutter/bin"

        yes | /workspace/flutter/bin/flutter doctor --android-licenses

        /workspace/flutter/bin/flutter doctor -v

        /workspace/flutter/bin/flutter pub get

        /workspace/flutter/bin/flutter build appbundle --release --no-pub --target-platform android-arm64 --target-platform android-arm

artifacts:
  objects:
    location: 'gs://mega-editor-builds-7-7carlos/build_artefacts/${BUILD_ID}'
    paths:
      - 'build/app/outputs/bundle/release/app-release.aab'

options:
  logging: CLOUD_LOGGING_ONLY
