steps:
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        # Comandos aquí...

artifacts:
  objects:
    location: 'gs://mega-editor-builds-7-7carlos/build_artefacts/${BUILD_ID}'
    paths:
      - 'build/app/outputs/bundle/release/app-release.aab'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s  # <- Aquí, al mismo nivel que steps, artifacts y options
