steps:
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        # ---- Configuración del Entorno de Build ----
        
        # Actualiza e instala dependencias
        apt-get update && apt-get install -y unzip curl git openjdk-17-jdk

        # Define versión de Flutter
        FLUTTER_VERSION='3.22.0-stable'

        # Descarga y extrae Flutter
        curl -O https://storage.googleapis.com/flutter_releases/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}.tar.xz
        tar xvf flutter_linux_${FLUTTER_VERSION}.tar.xz --directory /workspace/

        # Configura PATH de Flutter
        export PATH="$PATH:/workspace/flutter/bin"

        # Acepta licencias de Android
        yes | /workspace/flutter/bin/flutter doctor --android-licenses

        # Verifica entorno
        /workspace/flutter/bin/flutter doctor -v

        # ---- Build de Flutter ----
        
        # Obtiene dependencias
        /workspace/flutter/bin/flutter pub get

        # Compila App Bundle
        /workspace/flutter/bin/flutter build appbundle --release --no-pub --target-platform android-arm64 --target-platform android-arm

artifacts:
  objects:
    location: 'gs://mega-editor-builds-7-7carlos/build_artefacts/${BUILD_ID}'
    paths:
      - 'build/app/outputs/bundle/release/app-release.aab'
