steps:
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        # Instalamos dependencias
        apt-get update && apt-get install -y unzip curl git openjdk-17-jdk
        
        # Definimos la versión usando una variable de shell (no una sustitución de Cloud Build)
        export FLUTTER_VERSION="3.22.0-stable"
        
        # Descargamos y extraemos Flutter
        curl -O https://storage.googleapis.com/flutter_releases/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}.tar.xz
        tar xvf flutter_linux_${FLUTTER_VERSION}.tar.xz --directory /workspace/
        
        # Exportamos la ruta y ejecutamos comandos de Flutter
        export PATH="$PATH:/workspace/flutter/bin"
        yes | flutter doctor --android-licenses
        flutter doctor -v
        flutter pub get
        flutter build appbundle --release --no-pub --target-platform android-arm64

artifacts:
  objects:
    location: 'gs://mega-editor-builds-7-7carlos/build_artefacts/${BUILD_ID}'
    paths:
      - 'build/app/outputs/bundle/release/app-release.aab'

options:
  logging: CLOUD_LOGGING_ONLY
