name: mega_editor_ultra
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Database (Drift)
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.0 # Para la base de datos nativa en Android/iOS
  path_provider: ^2.0.15 # Para encontrar rutas de archivos
  path: ^1.9.1 # Utilidades de rutas

  # Permissions
  permission_handler: ^11.3.1

  # File Picker
  file_picker: ^8.0.0

  # Multimedia Editing (FFmpeg)
  ffmpeg_kit_flutter_min_gpl: ^6.0.0 # Versión con GPL para más codecs. ¡Confirmado como estable!

  # Audio Playback
  just_audio: ^0.9.38
  audio_session: ^0.1.18 # Para gestionar sesiones de audio

  # Video Playback
  better_player: ^0.0.8

  # Navigation
  go_router: ^14.0.2

  # UI Enhancements
  google_fonts: ^6.2.1

  # YouTube Player
  youtube_player_flutter: ^9.0.0

  # Webview
  webview_flutter: ^4.7.0

  # Camera
  camera: ^0.10.5+9

  # Firebase (para Marketplace y Colaboración)
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  # firebase_auth: ^4.19.0 # Consideraremos añadir esto si la colaboración requiere autenticación

  model_viewer_plus: ^1.9.3 # ¡Confirmado como estable y necesario!

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6 # Mantener

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Mantener o actualizar

  # Code Generation (Drift & Riverpod)
  drift_dev: ^2.17.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.5

flutter:

  # Habilitar generación de localización
  generate: true

  # Assets (añadidos en el Paso 4)
  assets:
    - assets/
    - assets/ar_models/ # Para modelos AR
